### PR TITLE
Add missing LCSH ID

### PR DESCRIPTION
**Pull request by bentley**

### CODE REVIEW

**Comment by acabal** [comment]
All of these IDs were supposedly missed by create-draft. How did you find them?

**Comment by bentley** [comment]
I found these by eyeballing the unknown terms. There may be more, it wasn’t an exhaustive check.

As for the cause: I haven’t confirmed that this can happen, but my theory for at least some of them is that the correct term showed up in the second page or later in the search results, and create-draft only checked the first page.

**Comment by acabal** [comment]
Is that actually the case? If so, then we should update create-draft. But it could make it take much longer if it has to execute and parse N more http requests for each unknown subject. So if we update it, I want to be really sure that that's what's going on. I don't understand why a query at LoC for "fairy tales" wouldn't return "fairy tales" on the first page of the results.

**Comment by bentley** [comment]
I can’t guarantee that’s what happened in some or all of these cases. However, I did just try `https://id.loc.gov/search/?q=cs:http://id.loc.gov/authorities/subjects&q="Science+Fiction"` (case significant?), and “Science fiction” (sh85118629) came up third, after “Science fiction, Singaporean (English)” and “Science fiction, Salvadoran”. (Not sure if create-draft encodes space as + or %20 but got the same results either way.)

If “Science fiction” can show up below two entries of that name pattern, I think it’s safe to assume that it can show up below twenty‐one of them.

I don’t have any better guesses or alternative strategies. Using the [bulk downloads](https://id.loc.gov/download/) is obviously not workable for create-draft. Unless someone decides to set up a server for SE with a custom ID search using the LOC XML dumps as the backend…

**Pull request merged**
